### ISSUE TITLE
Density & Breach are still incompatible after installing the mod.

### ISSUE THREAD

**Issue by Ethanwu0608** [SmushyTaco/Expanded-Weapon-Enchanting#4]
Density & Breach are still incompatible after installing the mod.
![image](https://github.com/user-attachments/assets/4f3853a8-efe2-407b-8c65-18d7ce01e556)

**Comment by SmushyTaco** [comment]
This mod doesn't cover maces. It's for weapon enchantments that can go on a sword. A mod specifically for the mace will be made or the scope of this mod will be expanded sometime in the future.
